# Generated by Django 5.2.5 on 2025-08-25 04:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_demand_threshold', models.PositiveIntegerField(default=0, help_text='Bookings per week')),
                ('high_demand_threshold', models.PositiveIntegerField(default=10, help_text='Bookings per week')),
                ('low_demand_multiplier', models.DecimalField(decimal_places=2, default=0.8, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(2.0)])),
                ('normal_demand_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(2.0)])),
                ('high_demand_multiplier', models.DecimalField(decimal_places=2, default=1.3, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(2.0)])),
                ('demand_calculation_days', models.PositiveIntegerField(default=7, help_text='Days to look back for demand calculation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_pricing', to='equipment.equipmenttype')),
            ],
            options={
                'verbose_name': 'Demand Pricing',
                'verbose_name_plural': 'Demand Pricing',
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('seasonal', 'Seasonal'), ('demand', 'Demand-based'), ('duration', 'Duration-based'), ('location', 'Location-based'), ('equipment_type', 'Equipment Type'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of days (0=Monday, 6=Sunday)')),
                ('latitude_min', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude_max', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_min', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_max', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hourly_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)])),
                ('daily_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)])),
                ('weekly_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)])),
                ('monthly_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)])),
                ('fixed_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_weekly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='equipment.equipment')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='equipment.equipmenttype')),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('demand_level', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], max_length=20)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_history', to='equipment.equipment')),
                ('pricing_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.pricingrule')),
            ],
            options={
                'verbose_name': 'Pricing History',
                'verbose_name_plural': 'Pricing History',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.CharField(choices=[('planting', 'Planting Season'), ('growing', 'Growing Season'), ('harvesting', 'Harvesting Season'), ('off_season', 'Off Season'), ('peak', 'Peak Season'), ('low', 'Low Season')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hourly_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)])),
                ('daily_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)])),
                ('fixed_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_pricing', to='equipment.equipmenttype')),
            ],
            options={
                'verbose_name': 'Seasonal Pricing',
                'verbose_name_plural': 'Seasonal Pricing',
                'ordering': ['start_date'],
            },
        ),
    ]
