# Generated by Django 5.2.5 on 2025-08-25 04:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('tractor', 'Tractor'), ('harvester', 'Harvester'), ('planter', 'Planter'), ('irrigation', 'Irrigation'), ('sprayer', 'Sprayer'), ('tillage', 'Tillage'), ('transport', 'Transport'), ('other', 'Other')], max_length=50)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('base_daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance_interval_hours', models.PositiveIntegerField(default=100, help_text='Hours between maintenance')),
                ('maintenance_interval_days', models.PositiveIntegerField(default=30, help_text='Days between maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specifications as JSON')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features as JSON')),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year_manufactured', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('other', 'Other')], max_length=20)),
                ('fuel_consumption', models.DecimalField(blank=True, decimal_places=2, help_text='Liters per hour', max_digits=5, null=True)),
                ('capacity', models.CharField(blank=True, help_text='Equipment capacity (e.g., HP, tons, etc.)', max_length=100)),
                ('total_hours', models.PositiveIntegerField(default=0, help_text='Total operating hours')),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('minimum_booking_hours', models.PositiveIntegerField(default=1)),
                ('maximum_booking_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_equipment', to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipment.equipmenttype')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipment_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipment.equipment')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('equipment_condition', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('operator_skill', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_for_money', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='equipment.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('equipment', 'user', 'booking')},
            },
        ),
    ]
