# Generated by Django 5.2.5 on 2025-10-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='state',
        ),
    ]
