# Generated by Django 5.2.7 on 2025-10-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_address_remove_equipment_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='total_kilometers',
            field=models.PositiveIntegerField(default=0, help_text='Total kilometers covered by this equipment'),
        ),
    ]
