# Generated by Django 5.2.5 on 2025-10-25 09:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
        ('equipment', '0003_equipment_total_kilometers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.DecimalField(decimal_places=2, help_text='Actual hours the equipment was used', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('kilometers_covered', models.DecimalField(decimal_places=2, default=0, help_text='Distance covered in kilometers', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel_consumed', models.DecimalField(decimal_places=2, default=0, help_text='Fuel consumed in liters', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('operating_temperature_avg', models.DecimalField(blank=True, decimal_places=2, help_text='Average operating temperature in Celsius', max_digits=5, null=True)),
                ('load_factor', models.DecimalField(decimal_places=2, default=50, help_text='Average load as percentage of capacity', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('terrain_type', models.CharField(choices=[('flat', 'Flat'), ('hilly', 'Hilly'), ('rough', 'Rough Terrain'), ('mixed', 'Mixed')], default='flat', max_length=20)),
                ('idle_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Hours equipment was idle but running', max_digits=6)),
                ('error_count', models.PositiveIntegerField(default=0, help_text='Number of errors/warnings during operation')),
                ('operator_notes', models.TextField(blank=True, help_text='Any issues or observations during use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_log', to='bookings.booking')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Equipment Usage Log',
                'verbose_name_plural': 'Equipment Usage Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_failure_probability', models.DecimalField(decimal_places=2, default=0, help_text='Probability of failure in percentage (0–100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('days_until_maintenance', models.PositiveIntegerField(default=0, help_text='Estimated days until maintenance is needed')),
                ('predicted_maintenance_date', models.DateField(default=django.utils.timezone.now, help_text='Predicted date when maintenance will be needed')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=20)),
                ('components_at_risk', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('features_used', models.JSONField(blank=True, default=dict)),
                ('recommended_actions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_predictions', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Maintenance Prediction',
                'verbose_name_plural': 'Maintenance Predictions',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('upcoming', 'Upcoming Maintenance'), ('overdue', 'Overdue Maintenance'), ('high_risk', 'High Risk Alert'), ('critical', 'Critical Alert')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_to_owner', models.BooleanField(default=False)),
                ('sent_to_admins', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_alerts', to='equipment.equipment')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='maintenance.maintenanceprediction')),
            ],
            options={
                'verbose_name': 'Maintenance Alert',
                'verbose_name_plural': 'Maintenance Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive Maintenance'), ('corrective', 'Corrective Maintenance'), ('predictive', 'Predictive Maintenance'), ('emergency', 'Emergency Repair')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(help_text='Description of maintenance work')),
                ('work_performed', models.TextField(blank=True, help_text='Detailed work performed')),
                ('parts_replaced', models.JSONField(blank=True, default=list, help_text='List of parts replaced')),
                ('equipment_hours_at_maintenance', models.PositiveIntegerField(default=0, help_text='Total equipment hours when maintenance was performed')),
                ('kilometers_at_maintenance', models.PositiveIntegerField(default=0, help_text='Total kilometers when maintenance was performed')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('performed_by', models.CharField(help_text='Technician or service center name', max_length=200)),
                ('issues_found', models.TextField(blank=True, help_text='Any issues discovered during maintenance')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('next_maintenance_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenance', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceprediction',
            index=models.Index(fields=['equipment', '-predicted_at'], name='maintenance_equipme_bf6683_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceprediction',
            index=models.Index(fields=['risk_level'], name='maintenance_risk_le_0c1d97_idx'),
        ),
    ]
