# Generated by Django 5.2.5 on 2025-10-25 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20251026_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentusagelog',
            name='error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipmentusagelog',
            name='fuel_consumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='equipmentusagelog',
            name='hours_used',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='equipmentusagelog',
            name='idle_time_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='equipmentusagelog',
            name='kilometers_covered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='equipmentusagelog',
            name='load_factor',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='equipmentusagelog',
            name='operating_temperature_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentusagelog',
            name='operator_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenanceprediction',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='maintenanceprediction',
            name='days_until_maintenance',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='maintenanceprediction',
            name='predicted_failure_probability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='maintenanceprediction',
            name='predicted_maintenance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='equipment_hours_at_maintenance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='issues_found',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='kilometers_at_maintenance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='parts_replaced',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_by',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='scheduled_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='work_performed',
            field=models.TextField(blank=True),
        ),
    ]
